remote_theme: jasongrimes/jekyll-chapterbook

title: Mastering Identus
longtitle: Mastering Identus: A Developer's Handbook
author: Jon Bauer & Roberto Carvajal
email: jon@goodfuture.io
description: >
  A practical guide to creating Self Sovereign Identity Applications with Identus


