project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "posts/"
    - "!book/"

resources:
  - CNAME
  - README.md

website:
  title: "Mastering Identus: A Developer Handbook"
  page-footer: "Copyright 2024, Jon Bauer, Roberto Carvajal"
  site-url: https://identusbook.com
  description: "Mastering Identus: A Developer Handbook"
  navbar:
    background: primary
    search: true
    left:
      - text: "Blog"
        file: blog.qmd
      - href: book/index.html   
        text: "Book"
      - text: "Authors"
        file: authors.qmd
    right:
      - icon: github
        href: https://github.com/identusbook
        aria-label: GitHub
      - icon: rss
        href: index.xml
  sidebar:
    - title: "Book"
      contents:
        - book.qmd
        # navigation items

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



