project:
  type: website
  output-dir: website-source

website:
  title: "Mastering Identus: A Developer Handbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



