project:
  type: website
  output-dir: website-source

website:
  title: "Mastering Identus: A Developer Handbook"
  page-footer: "Copyright 2024, Jon Bauer, Roberto Carvajal"
  navbar:
    background: primary
    search: true
    left:
      - text: "News"
        file: news.qmd
      - text: "Book"
        file: book.qmd   
      - text: "Authors"
        file: authors.qmd

  sidebar:
    - title: "News"
      style: "docked"
      background: light
      contents:
        - news.qmd

    - title: "Book"
      contents:
        - book.qmd
        # navigation items

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



