project:
  type: website
  output-dir: website-source

website:
  title: "Mastering Identus: A Developer Handbook"
  page-footer: "Copyright 2024, Jon Bauer, Roberto Carvajal"
  site-url: https://identusbook.com
  description: "Mastering Identus: A Developer Handbook"
  navbar:
    background: primary
    search: true
    left:
      - text: "News"
        file: news.qmd
      - text: "Book"
        file: book.qmd   
      - text: "Authors"
        file: authors.qmd
    right:
      - icon: rss
        href: index.xml

  sidebar:
    - title: "Book"
      contents:
        - book.qmd
        # navigation items

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



