project:
  type: book
  output-dir: ../_site/book/

book:
  title: "Mastering Identus: A Developer Handbook"
  author: "Jon Bauer, Roberto Carvajal"
  date: "04/05/2024"
  page-navigation: true
  search:
    location: sidebar
  sidebar:
    style: "docked"
    search: true
  navbar:
    logo-href: https://identusbook.com
    background: primary
    left:
      - href: https://identusbook.com/blog.html
        text: "Blog"
      - href: https://identusbook.com/book/index.html   
        text: "Book"
      - href: https://identusbook.com/authors.html
        text: "Authors"
    right:
      - icon: github
        href: https://github.com/identusbook
        aria-label: GitHub
      - icon: rss
        href: https://identusbook.com/index.xml

  chapters:
    - index.qmd
    - part: "Section I"
      chapters:
      - section1/preface.qmd
      - section1/introduction.qmd
      - section1/ssi-basics.qmd
      - section1/identus-concepts.qmd
    - part: "Section II - Getting Started"
      chapters:
      - section2/installation-dev.qmd
    - part: "Section III - Building"
      chapters: 
      - section3/project-overview.qmd
      - section3/wallets.qmd
      - section3/dids.qmd
      - section3/diddocuments.qmd
      - section3/connections.qmd
      - section3/verifiable-credentials.qmd
      - section3/didcomm.qmd
      - section3/verification.qmd
      - section3/plugins.qmd
    - part: "Section IV - Deploy"
      chapters: 
      - section4/installation-production.qmd
      - section4/maintenance.qmd
    - part: "Section V - Addendum"
      chapters: 
      - section5/trust-registries.qmd
      - section5/continuing-your-journey.qmd
    - part: "Appendices"
      chapters:
        - errata.qmd
        - glossary.qmd

#bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    toc: true
    number-sections: false
    documentclass: scrbook
    papersize: letter
  #epub:
  #  cover-image: cover.png
