project:
  type: book
  output-dir: ../_site/book/

book:
  title: "Mastering Identus: A Developer Handbook"
  author: "Jon Bauer, Roberto Carvajal"
  date: "04/05/2024"
  page-navigation: true
  search:
    location: sidebar
  sidebar:
    style: "docked"
    search: true
  navbar:
    logo-href: https://identusbook.com
    background: primary
    left:
      - href: https://identusbook.com/blog.html
        text: "Blog"
      - href: https://identusbook.com/book/index.html   
        text: "Book"
      - href: https://identusbook.com/authors.html
        text: "Authors"
    right:
      - icon: github
        href: https://github.com/identusbook
        aria-label: GitHub
      - icon: rss
        href: https://identusbook.com/index.xml

  chapters:
    - index.md
    - copyright.md
    - license.md
    - dedication.md
    - preface.md
    - part: "Section I"
      chapters:
      - section1/introduction.md
      - section1/ssi-basics.md
      - section1/dids-and-diddocuments.md
      - section1/identus-concepts.md
    - part: "Section II - Getting Started"
      chapters:
      - section2/installation-local.md
      - section2/agent-rest-api.md
      - section2/mediator.md
    - part: "Section III - Building"
      chapters: 
      - section3/project-overview.md
      - section3/wallets.md
      - section3/didcomm.md
      - section3/connections.md
      - section3/verifiable-credentials.md
      - section3/verification.md
    - part: "Section IV - Deploy"
      chapters: 
      - section4/installation-production.md
      - section4/maintenance.md
    - part: "Section V - Addendum"
      chapters: 
      - section5/trust-registries.md
      - section5/continuing-your-journey.md
    - part: "Appendices"
      chapters:
        - errata.md
        - glossary.md

#bibliography: references.bib

format:
  html:
    theme: flatly
    code-overflow: wrap
  pdf:
    toc: true
    number-sections: false
    documentclass: scrbook
    papersize: letter
  #epub:
  #  cover-image: cover.png
